### ISSUE TITLE
Ajouter la propriété `font-display` pour améliorer la performance

### ISSUE THREAD

**Issue by jhauck67** [jhauck67/Projet-Gaming-Campus#4]
Il faut ajouter la propriété `font-display: swap;` au selecteur ` @font-face`
```css
@font-face {
    font-display: swap;
}
```
